#!/usr/bin/env python

# Usage example: ./create-gremlin uat
import os
import sys

import boto3

my_dir = os.path.dirname(os.path.realpath(__file__))
sys.path.append(os.path.join(my_dir, os.pardir))
import util


env_id = sys.argv[1]
util.verify_setup([env_id])

env = util.load_config()["env"][env_id]
ec2 = boto3.resource('ec2', region_name=env["region"])

sg_opts = []  # Gremlin doesn't need any inbound connections
user_data = open(os.path.join(my_dir, "launch-gremlin")).read().format(
    storage_hostname=util.get_hostname(ec2, env_id, env["cassandraRole"])
)

run_instance_opts = {
    "UserData": user_data,
    "InstanceType": "t2.micro",
}

util.create_instance(env_id, "gremlin", sg_opts, run_instance_opts, ["cassandraClient"])
