#!/usr/bin/env python

# Usage example: ./restore-cassandra uat 2016-11-01T13:27:33.292388
import os
import sys

import boto3

my_dir = os.path.dirname(os.path.realpath(__file__))
sys.path.append(os.path.join(my_dir, os.pardir))
import util


ROLE = "cassandra"


env_id = sys.argv[1]
util.verify_setup([env_id])

snapshot_id = sys.argv[2]
env = util.load_config()["env"][env_id]
ec2 = boto3.resource("ec2", region_name=env["region"])

print "Stopping platform services..."
instance_platform, = util.get_instances(ec2, env_id, "platform")
runner_platform = util.RemoteRunner(env, instance_platform)
runner_platform.run("cd scripts && ./stop-services-platform")

print "Syncing scripts to Cassandra..."
instance, = util.get_instances(ec2, env_id, ROLE)
util.sync_remote_scripts(env_id, ROLE)

print "Restoring snapshot..."
runner = util.RemoteRunner(env, instance)
runner.run("scripts/restore-cassandra-snapshot {env_id} {snapshot_id}".format(
    env_id=env_id,
    snapshot_id=snapshot_id
))


print "Restarting platform services..."
runner_platform.run("cd scripts && ./update-services-platform")

print "Snapshot restored."
