#!/usr/bin/env python
import subprocess
import sys

import boto3

my_dir = os.path.dirname(os.path.realpath(__file__))
sys.path.append(os.path.join(my_dir, os.pardir))
import util

env_id = sys.argv[1]
util.verify_setup([env_id])

env = util.load_config()["env"][env_id]
client = boto3.client('ec2', region_name=env["region"])
ec2 = boto3.resource('ec2', region_name=env["region"])

print "Creating Convox rack..."
rack_name = util.resource_name(env_id, "convox")
subprocess.check_call([
    "convox",
    "install",
    "--email", util.get_my_email(),
    "--stack-name", rack_name,
    "--region", env["region"],
    "--existing-vpc", env["convox"]["vpc"],
    "--internet-gateway", env["convox"]["internetGateway"],
    "--vpc-cidr", env["convox"]["vpcCidr"],
    "--subnet-cidrs", ",".join(env["convox"]["subnetCidrs"]),
])

print "Successfully created Convox rack."
