#!/usr/bin/env python
import json
import os
import sys

import util

env_id = sys.argv[1]
util.verify_setup([env_id])

my_dir = os.path.dirname(os.path.realpath(__file__))

env_vars = json.loads(util.get_env_vars(env_id))

sg_opts = [
    ("kafkaClient", None),
    ("kafka", {
        "IpPermissions": [
            {
                "IpProtocol": "tcp",
                "FromPort": 9092,
                "ToPort": 9092,
                "UserIdGroupPairs": [{
                    "GroupName": util.resource_name(env_id, "kafkaClient")
                }]
            }
        ]
    }),
]

launch_script = open(os.path.join(my_dir, "launch-kafka")).read().format(
    env_id=env_id,
    dd_api_key=env_vars["datadog"]["apiKey"],
)
run_instance_opts = {
    "UserData": launch_script,
    "InstanceType": "m4.xlarge",
}

util.create_instance(env_id, "kafka", sg_opts, run_instance_opts)