#!/usr/bin/env python
import sys

import boto3

import util


env_id = sys.argv[1]
util.verify_setup([env_id])

env = util.load_config()["env"][env_id]

ec2 = boto3.resource('ec2', region_name=env["region"])
instances = util.get_instances(ec2, env_id)
for instance in instances:
    tags = util.simplify_tags(instance.tags)
    print instance.id, tags["Name"], tags.get("Role"), instance.public_ip_address, instance.state["Name"]
