#!/usr/bin/env python

# Usage example: ./backup-cassandra uat
import os
import sys

import boto3

my_dir = os.path.dirname(os.path.realpath(__file__))
sys.path.append(os.path.join(my_dir, os.pardir))
import util


ROLE = "cassandra"


env_id = sys.argv[1]
util.verify_setup([env_id])

env = util.load_config()["env"][env_id]
ec2 = boto3.resource('ec2', region_name=env["region"])

print "Finding instances..."
instance, = util.get_instances(ec2, env_id, ROLE)

print "Syncing scripts..."
util.sync_remote_scripts(env_id, ROLE)

print "Taking snapshot..."
runner = util.RemoteRunner(env, instance)
runner.run("scripts/snapshot-cassandra {}".format(env_id))

print "Snapshot taken."
