#!/usr/bin/env python

# Usage example: ./create-cassandra-user uat
import os
import sys

my_dir = os.path.dirname(os.path.realpath(__file__))
sys.path.append(os.path.join(my_dir, os.pardir))
import util

env_id = sys.argv[1]
util.verify_setup([env_id])

util.create_user(env_id, "cassandra", ["arn:aws:iam::aws:policy/AmazonS3FullAccess"])
