#!/usr/bin/env python
import sys

import boto3

import util

env_id = sys.argv[1]
util.verify_setup([env_id])

env = util.load_config()["env"][env_id]
ec2 = boto3.resource('ec2', region_name=env["region"])

client = boto3.client('ec2', region_name=env["region"])

print "Deleting security group..."
sgs = util.get_sgs(ec2, env_id, "ssh")
for sg in sgs:
    print "Deleting", sg
    sg.delete()

print "Successfully deleted SSH security group."
