#!/usr/bin/env python
import sys

import boto3
from botocore.exceptions import ClientError

import util

ROLE = "modelsStore"

env_id = sys.argv[1]
util.verify_setup([env_id])

env = util.load_config()["env"][env_id]
client_ec2 = boto3.client("ec2", region_name=env["region"])
client_elasticache = boto3.client("elasticache", region_name=env["region"])
ec2 = boto3.resource('ec2', region_name=env["region"])

name = util.resource_name(env_id, ROLE)

print "Terminating Elasticache cluster..."
try:
    client_elasticache.delete_cache_cluster(CacheClusterId=name)
except ClientError as e:
    if "CacheClusterNotFound" in str(e):
        print "No Elasticache cluster found..."
    else:
        raise e
else:
    print "Waiting for Elasticache cluster to terminate..."
    waiter = client_elasticache.get_waiter('cache_cluster_deleted')
    waiter.wait(CacheClusterId=name)

print "Deleting security groups..."
util.delete_sg(ec2, env_id, "modelsStore")
util.delete_sg(ec2, env_id, "modelsStoreClient")

print "Successfully deleted Models Store."
