#!/usr/bin/env python
import sys

import util
env_id = sys.argv[1]

# Don't parse or validate here b/c we want to still be able to edit broken vars
# For the same reason, don't try to do verify_setup w/ this env
util.verify_setup([])
print util.get_env_vars(env_id)
